#ifndef SERVICES_ID_HPP
#define SERVICES_ID_HPP

#define BACKEND_SERVER_SERVICE_ID 0x1234
#define BACKEND_SERVER_INSTANCE_ID 0x5678
#define BACKEND_SERVER_METHOD_ID 0x0421


#define BACKEND_SERVER_DOWNLOAD_FILE_SERVICE_ID 0x1235
#define BACKEND_SERVER_DOWNLOAD_FILE_INSTANCE_ID 0x5679
#define BACKEND_SERVER_DOWNLOAD_FILE_METHOD_ID 0x0422

#endif // SERVICES_ID_HPP