#ifndef SERVICES_ID_HPP
#define SERVICES_ID_HPP

#define BACKEND_SERVER_SERVICE_ID 0x1234
#define BACKEND_SERVER_INSTANCE_ID 0x5678

#define BACKEND_SERVER_METHOD_ID 0x0421
#define BACKEND_SERVER_CHECK_INTERNET_CONNECTION_METHOD_ID 0x0441

#endif // SERVICES_ID_HPP